fix: fix elastic search error on devstack
Fix for the error
```
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fbcfc03f640>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fbcfc03f640>: Failed to establish a new connection: [Errno 111] Connection refused)
Internal Server Error: /search/course_discovery/
```

Related issue was detected while migrating to Lilac in the ticket
https://youtrack.raccoongang.com/issue/ICNC-603